// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAorMB7Tm29m3mjBMw8s-m0Z-9sbfiQPtY',
    appId: '1:422800855248:web:12640c5f160fd71203ced5',
    messagingSenderId: '422800855248',
    projectId: 'planejamento-de-agendamento',
    authDomain: 'planejamento-de-agendamento.firebaseapp.com',
    storageBucket: 'planejamento-de-agendamento.appspot.com',
    measurementId: 'G-Y9330M8W1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpcuVCAnUqiMOEtcQ_K9UygvFc-Ptb80k',
    appId: '1:422800855248:android:33674f14b39daf3403ced5',
    messagingSenderId: '422800855248',
    projectId: 'planejamento-de-agendamento',
    storageBucket: 'planejamento-de-agendamento.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB03fIHSF3EbO1Y06zHQV1vR5BAbwK4Ufw',
    appId: '1:422800855248:ios:6413cbc6a9ca05cd03ced5',
    messagingSenderId: '422800855248',
    projectId: 'planejamento-de-agendamento',
    storageBucket: 'planejamento-de-agendamento.appspot.com',
    iosBundleId: 'com.example.loginFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB03fIHSF3EbO1Y06zHQV1vR5BAbwK4Ufw',
    appId: '1:422800855248:ios:6413cbc6a9ca05cd03ced5',
    messagingSenderId: '422800855248',
    projectId: 'planejamento-de-agendamento',
    storageBucket: 'planejamento-de-agendamento.appspot.com',
    iosBundleId: 'com.example.loginFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAorMB7Tm29m3mjBMw8s-m0Z-9sbfiQPtY',
    appId: '1:422800855248:web:1740a63a649b845103ced5',
    messagingSenderId: '422800855248',
    projectId: 'planejamento-de-agendamento',
    authDomain: 'planejamento-de-agendamento.firebaseapp.com',
    storageBucket: 'planejamento-de-agendamento.appspot.com',
    measurementId: 'G-8XFZXZG27K',
  );

}